# Project information
site_name: DFINITY Developer Network
site_description: DFINITY Developer Network
site_author: DFINITY
site_url: https://dfinity-labs.github.io/sdk-public

# Copyright
copyright: 'Copyright &copy; 2019. All rights reserved.'

# Navigation
nav:
  - Demonstration site: 'index.md'
  - Hello world (v0.1.0):
    - Introduction: 'v0.1.0/introduction.md'
    - Before you begin: 'v0.1.0/before-you-begin.md'
    - Prepare a local environment: 'v0.1.0/prepare-dev-env.md'
    - Build executables: 'v0.1.0/build-executables.md'
    - Start the client: 'v0.1.0/start-the-client.md'
    - Send a request: 'v0.1.0/send-a-request.md'
    - Remove the software: 'v0.1.0/remove-software.md'
  - Hello name (v0.2.0):
    - Introduction: 'v0.2.0/hello-name.md'
    - Before you begin: 'v0.2.0/before-you-begin-v2.md'
    - Download the SDK: 'v0.2.0/download-sdk.md'
    - Build the dfx executable: 'v0.2.0/build-dfx.md'
    - Start the client locally: 'v0.2.0/start-client-locally.md'  
    - Create WebAssembly canister: 'v0.2.0/create-wasm.md'
    - Send an argument to the canister: 'v0.2.0/send-argument.md'
    - View command-line usage: 'v0.2.0/view-usage-info.md'
    - Remove the software: 'v0.2.0/remove-software-v2.md' 
  - Questions or suggestions: contact-us.md

# Configuration
theme:
  name: material
  custom_dir: 'dev-theme'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'black'
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'
  logo: 'global-images/logo-white-text.svg'
  favicon: 'global-images/favicon.png'
  feature:
    tabs: true # change to true for horizontal and vertical navigation
  # 404 page
  static_templates:
    - 404.html

extra:
  social:
    - type: 'discourse'
      link: 'https://discourse.org/dfinity'
    - type: 'github'
      link: 'https://github.com/dfinity-labs'
    - type: 'twitter'
      link: 'https://twitter.com/dfinity'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/dfinity'
    - type: 'medium'
      link: 'https://medium.com/dfinity'
    - type: 'telegram'
      link: 'https://t.me/dfinity' 

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascripts/extra.js'

# Markdown and Python Markdown Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dfinity
      repo: dfinity-lab 
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde